### PR TITLE
[Fix #64] Fix `Minitest/GlobalExpectations` autocorrection for chained methods

### LINKED ISSUE #64: `Minitest/GlobalExpectations` cop needs method chain support
Thanks for releasing `rubocop-minitest 0.7.0` which implements #60.

I'd like to apply this cop to google-cloud-storage gem and found it needs method chain support.
 
## Expected behavior

`Minitest/GlobalExpectations` cop corrects method chain correctly.

## Actual behavior

`Minitest/GlobalExpectations` cop adds _() only the last method name then the test modified is getting error as follows.

```ruby
% ruby method_chain.rb
Fetching gem metadata from https://rubygems.org/..................
Resolving dependencies...
Using bundler 2.1.2
Using minitest 5.14.0
Run options: --seed 39348

# Running:

E

Finished in 0.000494s, 2024.2915 runs/s, 0.0000 assertions/s.

  1) Error:
Greeting#test_0001_must say hello world in lower case:
NameError: undefined local variable or method `downcase' for #<#<Class:0x00007f880341dce0>:0x00007f88033f45e8>
    method_chain.rb:25:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
%
```

## Steps to reproduce the problem

* Create a `method_chain.rb`
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem 'minitest'
end

# Avoid `Style/Documentation: Missing top-level class documentation comment.`
class Greeting
  def say_hello
    'Hello, World!'
  end
end

require 'minitest/autorun'
describe Greeting do
  before do
    @foo = Greeting.new
  end

  it 'must say hello world in lower case' do
    @foo.say_hello.downcase.must_equal 'hello, world!'
    # Actual auto correct result
    # @foo.say_hello._(downcase).must_equal 'hello, world!'
    #
    # Expected auto correct result
    # _(@foo.say_hello.downcase).must_equal 'hello, world!'
  end
end
```
* Install Ruby 2.7.0 (i.e. rbenv install 2.7.0 ; rbenv global 2.7.0)
* gem install rubocop-minitest
* Run `ruby method_chain.rb` to see if this file shows `DEPRECATED: global use of must_equal from method_chain.rb:25. Use _(obj).must_equal instead. This will fail in Minitest 6.` and finishes successfully
* `rubocop --require rubocop-minitest --only Minitest/GlobalExpectations method_chain.rb -a` to auto-correct `Minitest/GlobalExpectations` cop
* Run `ruby method_chain.rb`

## RuboCop version

```
% rubocop -V
0.80.0 (using Parser 2.7.0.3, running on ruby 2.7.0 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes https://github.com/rubocop-hq/rubocop-minitest/issues/64

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
This looks good to me. Can you add the changelog entry to the CHANGELOG.md?

**Comment by yahonda** [comment]
Thanks for creating a pull request. Really appreciated. I'm testing this pull request with google-cloud-storage and found it causes two failures as follows.

Also, Let me prepare exact steps to reproduce tonight and inform other matchers like `must_be_kind_of` and `wont_be`.

Here is the brief output:

- https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb

```
% git diff
diff --git a/google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb b/google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb
index dcac1ca25..2767f361f 100644
--- a/google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb
+++ b/google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb
@@ -22,7 +22,7 @@ describe Google::Cloud::Storage::Project, :anonymous, :mock_storage do
   it "raises when creating a bucket without authentication" do
     stub = Object.new
     def stub.insert_bucket *args
-      args.first.must_be_nil # project
+      _(args.first).must_be_nil # project
       raise Google::Apis::AuthorizationError.new("unauthorized", status_code: 401)
     end
     anonymous_storage.service.mocked_service = stub
@@ -33,7 +33,7 @@ describe Google::Cloud::Storage::Project, :anonymous, :mock_storage do
   it "raises when listing buckets without authentication" do
     stub = Object.new
     def stub.list_buckets *args
-      args.first.must_be_nil # project
+      _(args.first).must_be_nil # project
       raise Google::Apis::AuthorizationError.new("unauthorized", status_code: 401)
     end
     anonymous_storage.service.mocked_service = stub
@@ -53,7 +53,7 @@ describe Google::Cloud::Storage::Project, :anonymous, :mock_storage do

     mock.verify

-    bucket.name.must_equal bucket_name
+    _(bucket.name).must_equal bucket_name
     bucket.wont_be :lazy?
   end

@@ -71,10 +71,10 @@ describe Google::Cloud::Storage::Project, :anonymous, :mock_storage do

     mock.verify

-    files.size.must_equal num_files
+    _(files.size).must_equal num_files
     files.each do |file|
       file.must_be_kind_of Google::Cloud::Storage::File
-      file.user_project.must_be :nil?
+      _(file.user_project).must_be :nil?
     end
   end

@@ -93,8 +93,8 @@ describe Google::Cloud::Storage::Project, :anonymous, :mock_storage do

     mock.verify

-    file.name.must_equal file_name
-    file.user_project.must_be :nil?
+    _(file.name).must_equal file_name
+    _(file.user_project).must_be :nil?
     file.wont_be :lazy?
   end

% bundle exec ruby -w -Itest test/google/cloud/storage/project_anonymous_test.rb
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/google-api-client-0.37.2/lib/google/apis/core/api_command.rb:132: warning: assigned but unused variable - a
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/google-api-client-0.37.2/lib/google/apis/core/batch.rb:171: warning: assigned but unused variable - length
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:370: warning: assigned but unused variable - pathlen
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:51: warning: method redefined; discarding old initialize
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_cert
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_file
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_path
/Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/google-api-client-0.37.2/lib/google/apis/core/base_service.rb:215: warning: method redefined; discarding old client
Run options: --seed 26896

# Running:

FFDEPRECATED: global use of must_be_kind_of from test/google/cloud/storage/project_anonymous_test.rb:76. Use _(obj).must_be_kind_of instead. This will fail in Minitest 6.
DEPRECATED: global use of must_be_kind_of from test/google/cloud/storage/project_anonymous_test.rb:76. Use _(obj).must_be_kind_of instead. This will fail in Minitest 6.
DEPRECATED: global use of must_be_kind_of from test/google/cloud/storage/project_anonymous_test.rb:76. Use _(obj).must_be_kind_of instead. This will fail in Minitest 6.
.DEPRECATED: global use of must_be_kind_of from /Users/yahonda/.rbenv/versions/2.6.5/lib/ruby/2.6.0/delegate.rb:83. Use _(obj).must_be_kind_of instead. This will fail in Minitest 6.
.DEPRECATED: global use of wont_be from test/google/cloud/storage/project_anonymous_test.rb:57. Use _(obj).wont_be instead. This will fail in Minitest 6.
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/bucket.rb:2204: warning: instance variable @lazy not initialized
.DEPRECATED: global use of wont_be from test/google/cloud/storage/project_anonymous_test.rb:98. Use _(obj).wont_be instead. This will fail in Minitest 6.
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:1722: warning: instance variable @lazy not initialized
.

Finished in 0.013181s, 455.2007 runs/s, 1138.0017 assertions/s.

  1) Failure:
Google::Cloud::Storage::Project::anonymous::mock_storage#test_0002_raises when listing buckets without authentication [test/google/cloud/storage/project_anonymous_test.rb:41]:
[Google::Cloud::UnauthenticatedError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `_' for #<Object:0x00007fdb228ca5f0>">
---Backtrace---
test/google/cloud/storage/project_anonymous_test.rb:36:in `list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:76:in `block in list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:634:in `execute'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:75:in `list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:153:in `buckets'
test/google/cloud/storage/project_anonymous_test.rb:41:in `block (3 levels) in <main>'
---------------

  2) Failure:
Google::Cloud::Storage::Project::anonymous::mock_storage#test_0001_raises when creating a bucket without authentication [test/google/cloud/storage/project_anonymous_test.rb:30]:
[Google::Cloud::UnauthenticatedError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `_' for #<Object:0x00007fdb22901550>">
---Backtrace---
test/google/cloud/storage/project_anonymous_test.rb:25:in `insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:98:in `block in insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:634:in `execute'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:97:in `insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:378:in `create_bucket'
test/google/cloud/storage/project_anonymous_test.rb:30:in `block (3 levels) in <main>'
---------------

6 runs, 15 assertions, 2 failures, 0 errors, 0 skips
%
```

**Comment by tejasbubane** [comment]
@koic Added changelog.

**Comment by yahonda** [comment]
Here are steps to reproduce 2 failures at https://github.com/rubocop-hq/rubocop-minitest/pull/65#issuecomment-596883141 

Use Ruby 2.6.5 because google-cloud-ruby gem does not support Ruby 2.7 yet.
```
gem install bundler
git clone -b diag_rubocop_minitest_65 https://github.com/yahonda/google-cloud-ruby
cd google-cloud-ruby/google-cloud-storage/
bundle install
bundle exec rake test
bundle exec rubocop --only Minitest/GlobalExpectations -a
bundle exec ruby -w -Itest test/google/cloud/storage/project_anonymous_test.rb
```

**Comment by koic** [comment]
I haven't been able to look into the details yet, anyway the following stubing test seem to be the issue.

```diff
     stub = Object.new
     def stub.insert_bucket *args
-      args.first.must_be_nil # project
+      _(args.first).must_be_nil # project
       raise Google::Apis::AuthorizationError.new("unauthorized", status_code: 401)
     end
```

@yahonda I'm going to merge this PR. Can you open another new issue for this one?

**Comment by koic** [comment]
@tejasbubane Thank you for the patch!

**Comment by yahonda** [comment]
@koic Thanks for the investigation. Sure, Let me open a new issue. 

@tejasbubane Thanks for your pull requests!

**Pull request merged**
