### PR TITLE
Add autocorrect to `Rails/AssertEmptyLiteral` cop

### PR DESCRIPTION
**Pull request by fatkodima**
1. Added autocorrection
2. Also this cop was not implemented correctly as it should check against `assert_equal([], something)`, not `assert([], something)` - changed that

For reference: http://docs.seattlerb.org/minitest/Minitest/Assertions.html#method-i-assert

### CODE REVIEW

**Comment by fatkodima** [comment]
Rebased.

**Comment by koic** [comment]
> 1. Added autocorrection
> 2. Also this cop was not implemented correctly as it should check against `assert_equal([], something)`, not `assert([], something)` - changed that

I think that unsafe auto-correction could be added. But the `assert` method has been intentionally used.
https://github.com/rubocop-hq/rubocop-minitest/issues/32

I'm worried about changing behaviour for bad case.

**Comment by fatkodima** [comment]
> But the assert method has been intentionally used. #32

Aaaah, got it. 

Reverted the second part:
> Also this cop was not implemented correctly as it should check against assert_equal([], something), not assert([], something) - changed that

Marked unsafe autocorrection.

**Comment by koic** [comment]
Thank you!

**Pull request merged**
